# Generated by Django 2.2 on 2019-07-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_code', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('semister', models.CharField(max_length=100)),
                ('startid', models.IntegerField(default=1)),
                ('endid', models.IntegerField(default=1)),
            ],
        ),
    ]
