# Generated by Django 2.2 on 2019-07-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_auto_20190706_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Semister',
            new_name='Semester',
        ),
    ]
