# Generated by Django 2.2 on 2019-07-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0003_auto_20190711_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teaches',
            name='Section',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='Semester',
            field=models.CharField(max_length=30),
        ),
    ]
