# Generated by Django 2.2 on 2019-07-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0004_auto_20190712_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='s_id',
            field=models.IntegerField(default=0),
        ),
    ]
