# Generated by Django 2.2 on 2019-07-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0005_attendence_s_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='s_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='t_id',
            field=models.CharField(max_length=10),
        ),
    ]
