# Generated by Django 2.2 on 2019-07-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0006_auto_20190712_0319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='Section',
            new_name='section',
        ),
        migrations.AlterField(
            model_name='attendence',
            name='s_id',
            field=models.IntegerField(default=1),
        ),
    ]
